amamenteDoe/config/routes.rb
Rails.application.routes.draw do
  resources :information
  root 'amamente_doe#home'

  resources :stations

end

amamenteDoe/app/models/information.rb
class Information < ActiveRecord::Base

    has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/,
    :path => ':rails_root/public/assets/:id/:style/:basename:.:extension',
    :url => '/assets/:id/:style/:basename:.:extension'

    validates :title, presence: true
    validates :content, presence: true
    validates :date, presence: true
    validates :url_video, presence: true, :if => :is_video?
    
    validates :information_type, presence: true
    validates :category, presence: true, :numericality => { :greater_than => 0}


    def is_video?
      information_type == 2
    end

end

amamenteDoe/app/models/station.rb
class Station < ActiveRecord::Base

	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/,
  	:path => ':rails_root/public/assets/:id/:style/:basename:.:extension',
    :url => '/assets/:id/:style/:basename:.:extension'

    validates :name, presence: true
    validates :address, presence: true
    validates :latitude, presence: true
    validates :longitude, presence: true
    validates :cep, presence: true
    validates :phone, presence: true,
    		  :numericality => true,
              :length => { :minimum => 10, :maximum => 15 }
    validates :station_type, presence: true
    validates :image, presence: true

end

amamenteDoe/app/controllers/amamente_doe_controller.rb
class AmamenteDoeController < ApplicationController
  
  def home
  end
end

amamenteDoe/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

amamenteDoe/app/controllers/information_controller.rb
class InformationController < ApplicationController
  before_action :set_information, only: [:show, :edit, :update, :destroy]

  # GET /information
  # GET /information.json
  def index
    @information = Information.all
  end

  # GET /information/1
  # GET /information/1.json
  def show
  end

  # GET /information/new
  def new
    @information = Information.new
  end

  # GET /information/1/edit
  def edit
  end

  # POST /information
  # POST /information.json
  def create
    @information = Information.new(information_params)
    if @information.information_type == 1
        @information.url_video = ""
    end
    respond_to do |format|
      if @information.save
        format.html { redirect_to @information, notice: 'Information was successfully created.' }
        format.json { render :show, status: :created, location: @information }
      else
        format.html { render :new }
        format.json { render json: @information.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /information/1
  # PATCH/PUT /information/1.json
  def update
    respond_to do |format|
      if @information.update(information_params)
        format.html { redirect_to @information, notice: 'Information was successfully updated.' }
        format.json { render :show, status: :ok, location: @information }
      else
        format.html { render :edit }
        format.json { render json: @information.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /information/1
  # DELETE /information/1.json
  def destroy
    @information.destroy
    respond_to do |format|
      format.html { redirect_to information_index_url, notice: 'Information was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_information
      @information = Information.find(params[:id])
      if @information.information_type == 1
          @information.url_video = ""
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def information_params
      params.require(:information).permit(:title, :content, :date, :favorite, :url_video, :information_type, :category, :image)
    end
end

amamenteDoe/app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :set_station, only: [:show, :edit, :update, :destroy]

  add_breadcrumb "home", :root_path
  add_breadcrumb "Nova estação", :stations_path

  # GET /stations
  # GET /stations.json
  def index
    @stations = Station.all
  end

  # GET /stations/1
  # GET /stations/1.json
  def show
  end

  # GET /stations/new
  def new
    @station = Station.new
  end

  # GET /stations/1/edit
  def edit
  end

  # POST /stations
  # POST /stations.json
  def create
    @station = Station.new(station_params)

    respond_to do |format|
      if @station.save
        format.html { redirect_to @station, notice: 'Station was successfully created.' }
        format.json { render :show, status: :created, location: @station }
      else
        format.html { render :new }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stations/1
  # PATCH/PUT /stations/1.json
  def update
    respond_to do |format|
      if @station.update(station_params)
        format.html { redirect_to @station, notice: 'Station was successfully updated.' }
        format.json { render :show, status: :ok, location: @station }
      else
        format.html { render :edit }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stations/1
  # DELETE /stations/1.json
  def destroy
    @station.destroy
    respond_to do |format|
      format.html { redirect_to stations_url, notice: 'Station was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_station
      @station = Station.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def station_params
      params.require(:station).permit(:name, :address, :latitude, :longitude, :cep, :phone, :fax, :station_type, :image)
    end
end

amamenteDoe/app/helpers/amamente_doe_helper.rb
module AmamenteDoeHelper
end

amamenteDoe/app/helpers/application_helper.rb
module ApplicationHelper
end

amamenteDoe/app/helpers/information_helper.rb
module InformationHelper
end

amamenteDoe/app/helpers/stations_helper.rb
module StationsHelper

	def format_phone(num_phone)
		formatted_number = "("
		formatted_number << num_phone[0..1]
		formatted_number << ")"
		formatted_number << num_phone[2..5]
		formatted_number << "-"
		formatted_number << num_phone[6..9]
		formatted_number
	end

end

amamenteDoe/app/views/amamente_doe/home.html.erb
<%= render_breadcrumbs %>

<div class="center jumbotron">

<% provide(:title, "Home | ") %>

<p>Cadastro de informações e estações de amamentação</p>


  <%= link_to "Informações", 'information', class: "btn btn-lg btn-primary" %>
  <%= link_to "Estações", 'stations', class: "btn btn-lg btn-primary" %>
</div>

amamenteDoe/app/views/information/_form.html.erb
<%= bootstrap_form_for(@information) do |f| %>
  <% if @information.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@information.errors.count, "error") %> prohibited this information from being saved:</h2>

      <ul>
      <% @information.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="collection_radio_buttons">
    <%= f.form_group :information_type, label: {text: "Tipo de Informação"} do %>
      <%= f.radio_button :information_type, 1, label: "Texto"%>
      <%= f.radio_button :information_type, 2, label: "Video"%>
    <% end %>
  </div>
  <div class="field">
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.datetime_select :date %>
  </div>
  <!-- <div class="field">
    <%= f.check_box :favorite %>
  </div> -->
  <div class="field">
    <%= f.url_field :url_video %>
  </div>
  <div class="field">
    <%= f.number_field :category %>
  </div>
  <div class="field">
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

amamenteDoe/app/views/information/edit.html.erb
<h1>Editing Information</h1>

<%= render 'form' %>

<%= link_to 'Show', @information %> |
<%= link_to 'Back', information_index_path %>

amamenteDoe/app/views/information/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Information</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Date</th>
      <th>Favorite</th>
      <th>Url video</th>
      <th>Information type</th>
      <th>Category</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @information.each do |information| %>
      <tr>
        <td><%= information.title %></td>
        <td><%= information.content %></td>
        <td><%= information.date %></td>
        <td><%= information.favorite %></td>
        <td><%= information.url_video %></td>
        <td><%= information.information_type %></td>
        <td><%= information.category %></td>
        <td><%= information.image %></td>
        <td><%= link_to 'Show', information %></td>
        <td><%= link_to 'Edit', edit_information_path(information) %></td>
        <td><%= link_to 'Destroy', information, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Information', new_information_path %>

amamenteDoe/app/views/information/new.html.erb
<h1>New Information</h1>

<%= render 'form' %>

<%= link_to 'Back', information_index_path %>

amamenteDoe/app/views/information/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @information.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @information.content %>
</p>

<p>
  <strong>Date:</strong>
  <%= @information.date %>
</p>

<p>
  <strong>Favorite:</strong>
  <%= @information.favorite %>
</p>

<p>
  <strong>Url video:</strong>
  <%= @information.url_video %>
</p>

<p>
  <strong>Information type:</strong>
  <%= @information.information_type %>
</p>

<p>
  <strong>Category:</strong>
  <%= @information.category %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @information.image.url %>
</p>

<%= link_to 'Edit', edit_information_path(@information) %> |
<%= link_to 'Back', information_index_path %>

amamenteDoe/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <!-- The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a> -->
  </small>
  <nav>
    <ul>
      <!-- <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li> -->
    </ul>
  </nav>
</footer>

amamenteDoe/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Amamente e Doe", :root, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
       <!--  <li><%= link_to "Home",   '#' %></li>
        <li><%= link_to "Help",   '#' %></li>
        <li><%= link_to "Log in", '#' %></li> -->
      </ul>
    </nav>
  </div>
</header>

amamenteDoe/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

amamenteDoe/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title> <%= yield(:title) %>Amamente e Doe</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
	<%= render 'layouts/shim' %>
</head>
<body>

<%= render 'layouts/header' %>
<div class="container">
	<%= yield %>
	<%= render 'layouts/footer' %>

</div>

</body>
</html>

amamenteDoe/app/views/stations/_form.html.erb
<%= bootstrap_form_for(@station) do |f| %>
  <% if @station.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@station.errors.count, "error") %> prohibited this station from being saved:</h2>

      <ul>
      <% @station.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="collection_radio_buttons">
    <%= f.form_group :station_type, label: {text: "Tipo de Estação"} do %>
      <%= f.radio_button :station_type, 1, label: "Banco de leite"%>
      <%= f.radio_button :station_type, 2, label: "Posto de Leite"%>
    <% end %>
  </div>

  <div class="control-group">
    <%= f.text_field :name %>
  </div>
  <div class="control-group">
    <%= f.text_field :address %>
  </div>
  <div class="control-group">
    <%= f.text_field :latitude %>
  </div>
  <div class="control-group">
    <%= f.text_field :longitude %>
  </div>
  <div class="control-group">
    <%= f.text_field :cep %>
  </div>
  <div class="control-group">
    <%= f.telephone_field :phone %>
  </div>
  <div class="control-group">
    <%= f.text_field :fax %>
  </div>
 <!-- 
  <div class="control-group">
    <%= f.number_field :station_type %>
  </div>
  -->
  <div class="control-group">
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

amamenteDoe/app/views/stations/edit.html.erb
<h1>Editing Station</h1>

<%= render 'form' %>

<%= link_to 'Show', @station %> |
<%= link_to 'Back', stations_path %>

amamenteDoe/app/views/stations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de  Stations</h1>
<%= render_breadcrumbs %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Cep</th>
      <th>Phone</th>
      <th>Fax</th>
      <th>Station type</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stations.each do |station| %>
      <tr>
        <td><%= station.name %></td>
        <td><%= station.address %></td>
        <td><%= station.latitude %></td>
        <td><%= station.longitude %></td>
        <td><%= station.cep %></td>
        <td><%= station.phone %></td>
        <td><%= station.fax %></td>
        <td><%= station.station_type %></td>
        <td><%= image_tag(station.image.url(:thumb)) %></td>
        <td><%= link_to 'Show', station, :class => 'btn btn-mini' %></td>
        <td><%= link_to 'Edit', edit_station_path(station), :class => 'btn btn-mini' %></td>
        <td><%= link_to 'Destroy', station, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Station', new_station_path, :class => 'btn btn-primary' %>

amamenteDoe/app/views/stations/new.html.erb
<h1>New Station</h1>

<%= render 'form' %>

<%= link_to 'Back', stations_path %>

amamenteDoe/app/views/stations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @station.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @station.address %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @station.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @station.longitude %>
</p>

<p>
  <strong>Cep:</strong>
  <%= @station.cep %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @station.phone %>
</p>

<p>
  <strong>Fax:</strong>
  <%= @station.fax %>
</p>

<p>
  <strong>Station type:</strong>
  <%= @station.station_type %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @station.image.url %>
</p>

<%= link_to 'Edit', edit_station_path(@station) %> |
<%= link_to 'Back', stations_path %>